---
title: "Dashboard de filmes"
author: "Fernando Corrêa"
date: "01/02/2024"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)

library(tidyverse)

imdb <- read_csv2("dados/imdb2.csv")
```

# Introdução

Olá, boas-vindas! Este documento registra uma análise que fiz da base de dados IMDB. Abaixo temos algumas colunas dessa tabela para visualização:

```{r}
glimpse(imdb)
```

# Primeiras análises

Na visualização anterior podemos perceber que tem muitos valores faltantes (NA) nas colunas de receita. A tabela abaixo ilustra essas quantidades:

```{r}
imdb |> 
  summarise(
    total_de_filme = n(), 
    quantidade_receita_na = sum(is.na(receita)),
    percentual = paste0(
      round(quantidade_receita_na/total_de_filme*100, 2),
      "%")
  ) |> 
  knitr::kable(
    col.names = c("Total de filmes da base", "Quantidade de filmes sem receita", "Percentual de filmes sem receita"),
    align = "rrr"
  )
```

